# this only takes care of CD pipeline
# CI pipeline is taken care from github actions atm
version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "prepare"
  - "publish"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "codefresh-io/cube.js"
    revision: "${{CF_BRANCH}}"
    git: "cf_github"
    stage: "clone"

  install_dependencies:
    title: 'Installing testing dependencies'
    working_directory: ${{main_clone}}
    image: node:12.22.9
    commands:
      - ls
      - yarn install --frozen-lockfile
    stage: "prepare"

  build:
    title: 'Installing testing dependencies'
    working_directory: ${{main_clone}}
    image: node:12.22.9
    commands:
      - ls
      - yarn install --frozen-lockfile
    stage: "prepare"

  deploy_bigquery_driver_to_npm:
    title: 'Deploy bigquery-driver'
    type: npm-publish
    arguments:
      NPM_TOKEN: '${{NPM_TOKEN}}'
      DIR: 'cube.js/packages/cubejs-bigquery-driver'
    stage: "publish"

  deploy_postgres_driver_to_npm:
    title: 'Deploy postgres-driver'
    type: npm-publish
    arguments:
      NPM_TOKEN: '${{NPM_TOKEN}}'
      DIR: 'cube.js/packages/cubejs-postgres-driver'
    stage: "publish"

  deploy_server_core_to_npm:
    title: 'Deploy server-core'
    type: npm-publish
    arguments:
      NPM_TOKEN: '${{NPM_TOKEN}}'
      DIR: 'cube.js/packages/cubejs-server-core'
    stage: "publish"

