version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "install-dependencies"
  - "npm-publish"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "codefresh-io/cube.js"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "cf_github"
    stage: "clone"

  install_dependencies:
    title: 'Installing testing dependencies'
    image: node:12.22.9
    commands:
      - yarn install --frozen-lockfile
    stage: "install-dependencies"

  deploy_bigquery_driver_to_npm:
    title: 'Deploy bigquery-driver'
    type: npm-publish
    arguments:
      NPM_TOKEN: '${{NPM_TOKEN}}'
      DIR: 'cube.js/packages/cubejs-bigquery-driver'
    stage: "npm-publish"

