name: Build native

on:
  pull_request:
    paths:
      - '.github/workflows/rust-cubesql.yml'
      - 'packages/cubejs-backend-native/**'
      - 'rust/cubesql/**'
      - 'rust/cubesql/**'

jobs:
  lint:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    name: Check fmt/clippy

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-03-08
          override: true
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: ./rust/cubesql
          # default key
          key: cubesql-${{ runner.OS }}-x86_64-unknown-linux-gnu-16
          sharedKey: cubesql-${{ runner.OS }}-x86_64-unknown-linux-gnu-16
      - name: Lint CubeSQL
        run: cd rust/cubesql/cubesql && cargo fmt --all -- --check
      - name: Lint Native
        run: cd packages/cubejs-backend-native && cargo fmt --all -- --check
      - name: Clippy Native
        run: cd packages/cubejs-backend-native && cargo clippy -- -D warnings
      # CubeSQL is not ready for Clippy
      #- name: Clippy CubeSQL
      #  run: cd rust/cubesql && cargo clippy -- -D warnings
